### ISSUE TITLE
Pivot Unique: (Discussion)

### ISSUE THREAD

**Issue by swiftymarks** [vapor/fluent#189]
Is there anyway to mark Pivot as unique?

Example:
Like a user can only join one channel each.

Am not sure if this kind of feature is available in version Fluent 1.0

Thanks

**Comment by C0deH4cker** [comment]
You should probably use a parent relation instead of a pivot. You are describing a many (user) to one (channel) relation. In this case, you'd make the channel be the parent and user be the child. Pivots are intended to be used for many to many (sibling) relations. Refer to the [Vapor documentation page about Fluent relations](https://vapor.github.io/documentation/fluent/relation.html) for reference.

**Comment by swiftymarks** [comment]
@C0deH4cker just realized I was doing it the wrong way. Thanks for the help will try to implement the changes tonight. I will close this issue now
