### ISSUE TITLE
Live Cycle Event System

### ISSUE THREAD

**Issue by lennerd** [vapor/fluent#260]
# Feature Request

The current entity hocks are great, though there are defined per entity.

It would be nice to have some kind of event system for entity hooks to be able to add protocols like `SoftDeleteable`, `Timestampable`, `Versionable` etc. Currently similar existing protocols are tightly coupled with the query implementation.

As I'm quite new to Swift and Vapor I'm not sure how to solve this though.

**Comment by tanner0101** [comment]
I looked into this and it seems there is no great solution. The best I could come up with is having a static array in the Fluent library for each hook that you could append closures to. This has performance concerns as well as requires that code be executed to append to the hooks. This could potentially be achieved through Vapor providers, but it's not ideal. 

I'm adding this issue to the wishlist for Fluent 3. Until then, let's take each protocol (like `Versionable`) on a case by case basis.

Closing this issue here since it's a long term goal. Thanks for contributing!

**Comment by lennerd** [comment]
Thanks for looking into this!

Does it make sense to think about a Vapor wide event system we can use here?

**Comment by lennerd** [comment]
I'm thinking about something similar to the [Django Signals](https://docs.djangoproject.com/en/1.11/topics/signals/) or [Symfony EventDispatcher](http://symfony.com/doc/current/components/event_dispatcher.html) implementations.

**Comment by 0xTim** [comment]
Also worth noting that the queueing system would only work for each server that the app is deployed to - not the app across multiple servers. So you would still have issues when deployed across multiple instances

**Comment by lennerd** [comment]
I'm not really experienced with multiple server deployment. Is there a way for Vapor to "talk" between instances?

**Comment by 0xTim** [comment]
Yeah you can use any normal inter-server communication (probably just HTTP) but they you have timing issues and trying to keep everything in sync would be a nightmare

**Comment by lennerd** [comment]
Just thought about @0xTim comment again. Is queuing even a problem here? A event system would work similar to the current Middlewares in Vapor, executing code in response to creating, updating and deleting entities. So no need to talk between threads, no?
