### ISSUE TITLE
Rename `Entity.assertExists()`

### ISSUE THREAD

**Issue by bygri** [vapor/fluent#275]
# Rename `Entity.assertExists()`

* Author(s): [bygri](https://github.com/bygri)
* Status: **[Awaiting review](#rationale)**

## Introduction
[`assertExists()`](https://github.com/vapor/fluent/blob/master/Sources/Fluent/Entity/Entity.swift#L236) is a very convenient feature, but it's not clear from the name that it returns the entity's identifier, nor indeed anything at all. I'd like to suggest renaming it in a future release of Fluent to something more self-evident.

## Motivation

A developer can check that a model was saved properly like this:

```swift
try myModel.assertExists()
```

However this is a multi-use method, as it's also possible to shorthand creation of related models like this:

```swift
let category = Category()
try category.save()
let post = BlogPost(
  categoryId: try category.assertExists(),
)
```

In many languages, `assert` doesn't return. A newcomer to Vapor might be confused by there being a return value from `category.assertExists()`, and it being passed as an `Identifier`.

## Proposed solution

Ideally the invocation of this method should identify a) it returns the identifier, and b) a saved model must exist otherwise an error is thrown.

My top suggestion would be to simply rename it as `identifier()`. As a throwing method which returns a non-optional it would be reasonably clear from the call site how it functions.

```swift
let post = BlogPost(
  categoryId: try category.identifier(),
)
```

However I would also suggest retaining `assertExists()` without the return value, so that it can still function as a regular assert.

```swift
try myModel.assertExists()
```

## Suggested implementation

```swift
extension Entity {
    /// Asserts that the entity exists and returns
    /// its identifier.
    public func identifier() throws -> Identifier {
        guard let id = self.id else {
            throw EntityError.noId(Self.self)
        }

        guard exists else {
            throw EntityError.doesntExist(Self.self)
        }

        return id
    }
    /// Asserts that the entity exists
    public func assertExists() throws {
        let _ = try identifier()
    }
}
```

## Impact

Breaking change where `assertExists()` is used to fetch an identifier.

## Alternatives considered

Any of these would work, I think.

* `getIdentifier()`
* `getId()`
* `assertIdentifier()` would be better if the method were not split into two use cases.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tanner0101** [comment]
I agree the naming here is not super intuitive, however this is a convention that is being used across the framework now (`.assertSession()` for Sessions, `.assertUser()` for Auth). 

Using `.getFoo()` is not great because it isn't entirely clear that this will indeed throw if the value doesn't exist. The `get` prefix would be better for methods that return an optional. 

If we could find a better word than `assert` that conveys both the fact that the method will throw if the value is not found and that the value will be returned by the method, I would consider changing the usage of `assert` as a prefix throughout the framework. 

It's worth noting, too, that as Swift is a strongly-typed language we can rely on the language itself to make obvious that this method returns a value (for example you'll get unused result warnings if you just call assert). Unlike Javascript, we don't really _need_ to provide  context about what is returned in the name of the method. 

I think a better solution here could be an improvement in the documentation explaining the `.assert` prefix.

**Comment by bygri** [comment]
Possible alternatives to `assertX()`, attempting to convey both throwing and returning:

- `forceSession()`, `forceUser()`
- `requireSession()`, `requireUser()`

But should it remain with `assert`, which is still fine based on your justification above, perhaps `assertExists` itself should be renamed to `assertIdentifier` since the convention appears to be `assertNoun` where the noun is the returned value?

**Comment by tanner0101** [comment]
It's also asserting that `entity.exists == true`
