### ISSUE TITLE
ensure connections can be passed to relation queries

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent#289]
relations used within transactions need to be able to accept the connection from the transaction closure.

**Comment by ldamman** [comment]
I've opened a PR to not ignore the passed executor in the associations' makeQuery(_ executor: Executor) functions.

https://github.com/vapor/fluent/pull/292

Note that by using this pattern we'll have to return Query<C> from our association helpers instead of the more specific Children<P, C> as was done in the past.  I'm not sure if that's really an issue or not in the bigger picture, but it seemed worth noting.

**Comment by tanner0101** [comment]
I'd recommend continuing to return the relation and call `.makeQuery(conn)` at the point of use. You'll need the relation for things like `.add`, etc. 

Making this API smoother for passing connections through will definitely be addressed in Fluent 3.0.

Thanks for finding & fixing that bug!
