### ISSUE TITLE
Pipelined save()'s fail in RC2

### ISSUE THREAD

**Issue by jseibert** [vapor/fluent#411]
In reference to https://github.com/vapor/mysql/issues/143, this appears to be a higher level issue where pipelined queries now work, but save()'s do not.

Full test code to reproduce the issue:

```swift
public func boot(_ app: Application) throws {
    _ = try app.withConnection(to: .mysql) { (db) -> Future<Void> in
        let cat1 = TransactionCategory(name: "Category 1")
        let cat2 = TransactionCategory(name: "Category 2")
        
        return [
            cat1.save(on: db),
            cat2.save(on: db)
        ].flatten(on: db).transform(to: Void())

    }.wait()
}
```

This fails with:

```swift
error(⚠️ MySQL Error: Prepare response has invalid status: 1
- id: MySQLError.prepareStatus

File: /Users/jseibert/api/.build/checkouts/mysql.git-1890032512239690518/Sources/MySQL/Protocol/MySQLComStmtPrepareOK.swift
 - func: init(bytes:)
 - line: 25
 - column: 133
)
```

**Comment by tanner0101** [comment]
The specific issue with the invalid response is due to MySQL incorrectly handling query pipelining. See vapor/mysql#143 for that.

However, this issue did bring up another concern that Fluent needs to have its own concept of operation pipelining. Fluent must ensure a previous "operation" (or transaction maybe) is finished on a given connection before starting another one. This is because Fluent operations can span multiple db queries (such as an insert followed by a select).
