### ISSUE TITLE
Foreign Key Constraints issues should return a 400 instead of a 500

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#416]
Let's say you have a User model and a Todo model. There is a parent-child relationship between the two (users own todos). If you set up a foreign key constraint between the two and try and create a Todo model with the ID of a user that doesn't exist, currently you'll get a 500 Internal Server Error - this should be a 400 Bad Request

**Comment by 0xTim** [comment]
This should be the same for attempting to delete a model that can't be deleted due to FKC

**Comment by rafiki270** [comment]
or conflict/precondition failed?

**Comment by 0xTim** [comment]
Yeah think so

**Comment by tanner0101** [comment]
This will be difficult to do since Fluent has no concept of Vapor (and the AbortError there) and Vapor has no concept of Fluent (and FluentError).

Even if it were possible, the experience I've had working with other frameworks was that it's the developer's job to check foreign keys first before invoking the ORM. So it might make sense for Fluent to follow suit there.

**Comment by tanner0101** [comment]
Fluent 4 has a `DatabaseError` protocol that you can use to detect constraint errors. This allows you to catch them and return custom HTTP error responses. 

As for Vapor doing this by default, I don't see how that would be possible with the current ErrorMiddleware design. We can't conform protocols to protocols so `DatabaseError` can't be made to conform to `AbortError`. We also can't check for `DatabaseError` in ErrorMiddleware since Vapor doesn't import Fluent. We'd need some sort of error type registration system to achieve this. Perhaps that's worth pitching as a feature request to Vapor. 

Closing here since this is a limitation of Swift and/or Vapor's ErrorMiddleware.
