### ISSUE TITLE
Please bring back `addIndex`

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/fluent#515]
@tanner0101 why `addIndex` was deprecated and now it suggest to use `unique` instead?
Unique adds `UNIQUE INDEX`, but I need to add just `INDEX`. I understand that now I can do that only by calling raw query, but it's inconvenient..
Could you please bring it back at least for `FluentPostgreSQL`?

**Comment by MihaelIsaev** [comment]
ok, as we have what we have I wrote a workaround code

```swift
extension CarModel: Migration {
    public static func prepare(on connection: Database.Connection) -> Future<Void> {
        return Database.create(self, on: connection) { builder in
            try addProperties(to: builder)
            //builder.addIndex(to: \.idBrand) // deprecated! :cry: 
        }.flatMap { _ -> EventLoopFuture<Void> in
            return connection.query("CREATE INDEX idx_brand ON \"CarModels\" (\"idBrand\")").transform(to: ())
        }
    }
}
```
maybe it will help someone who faced with the same problem

**Comment by tanner0101** [comment]
Sorry for the inconvenience caused by `addIndex` going away. The problem is that adding just an `INDEX` column constraint during `CREATE TABLE` is not standard SQL. All SQL dialects _do_ support `UNIQUE` column constraint.

The standard for creating indexes is to issue a `CREATE INDEX` query. I will add support for building these queries to vapor/sql so that you can easily create and drop indexes using a SQL db. 👍

**Comment by MihaelIsaev** [comment]
@tanner0101 Thank you! 😊

**Comment by tanner0101** [comment]
Added :) Check the release for a preview of the syntax @MihaelIsaev https://github.com/vapor/postgresql/releases/tag/1.0.0-rc.4.2
