### ISSUE TITLE
Ability to add index when adding foreign key

### ISSUE THREAD

**Issue by kurabi** [vapor/fluent#534]
In databases like Postgres, when adding a foreign key, an index does not get automatically created, which is fine.

However the ability to add an index is important, specially when cascade update and cascade delete are set on the reference as a full table scan occurs when updating or deleting the referenced keys. See: 
https://www.cybertec-postgresql.com/en/postgresql-indexes-and-foreign-keys/

It would be nice if:
`reference(from:to:onUpdate:onDelete:)` was `reference(from:to:onUpdate:onDelete:createIndex:)`

Right now, you have to create the index separately, if you remember to.

**Comment by tanner0101** [comment]
If this issue is specific to PostgreSQL, we should raise the issue here: https://github.com/vapor/fluent-postgresql/. 

I think an overload with a signature like you mentioned would make sense. Another option could be issuing a warning in development mode that indexes could improve performance (if an FK but no index is added).

**Comment by tanner0101** [comment]
Track here: https://github.com/vapor/fluent-kit/issues/3
