### ISSUE TITLE
using .alsoDecode() with left/right joins

### ISSUE THREAD

**Issue by johnbona** [vapor/fluent#547]
Similar to the issue that @patchthecode posted in Discord, if you use `.alsoDecode()` with queries that use left/right joins, decoding can fail since the query can (rightly) return nil for the model/entity's columns.

Example query from @patchthecode:
```swift
Restaurant.query(on: req)
    .join(\User.id, to: \Restaurant.userId, method: .left)
    .join(\RestaurantReview.restaurantId, to: \Restaurant.id, method: .left)
    .alsoDecode(RestaurantReview.self)
    .alsoDecode(User.self).all()
```

Error that occurs when decoding:
```
[ ERROR ] PostgreSQLError.decode: Could not decode Int: null. (Logger+LogError.swift:17)
```

**Comment by sjorsvb** [comment]
I'm also running into this problem, are there any solutions yet?

**Comment by OHeroJ** [comment]
me too,  A left join B,  B is nil , will crash

**Comment by OHeroJ** [comment]
need help

**Comment by OHeroJ** [comment]
somebody do 

```swift
extension Contact {
struct NameOnly: Content {
    var id: Int?
    var type: String?
    var firstName: String?
    var surname: String?
    var companyName: String?
  }
}

// query.alsoDecode(Contact.NameOnly.self)
```

**Comment by tanner0101** [comment]
`alsoDecode` as implemented currently is meant for use with full joins. I think it would be possible to add support for LEFT / RIGHT joins, but that would be a non-trivial feature to add. The hard part would be deciding on logic for determining whether or not the joined model should be decoded. If all joined models are assumed to have primary keys, then that would be a good choice. But currently anything `Decodable` can be passed to `alsoDecode`.

**Comment by mattpolzin** [comment]
@tanner0101 what are your thoughts on supporting this by explicitly overloading the default implementations for `QueryBuilder.alsoDecode()` and `QuerySupporting.queryDecode()` to interpret `query.alsoDecode(Thing?.self)` as "decode or return nil" rather than "decode or throw." I have only done a little digging, but I think this could allow us to build a `join` query with a result where one of the tuple elements is optional (and nil if the joined row does not contain the information required to decode it).

This is not as cool as taking information on what type of `join` is being used and determining behavior based on that, but it should turn the example from the OP into

```
Restaurant.query(on: req)
    .join(\User.id, to: \Restaurant.userId, method: .left)
    .join(\RestaurantReview.restaurantId, to: \Restaurant.id, method: .left)
    .alsoDecode(RestaurantReview?.self)
    .alsoDecode(User?.self).all()
```
which I believe gives result type:
```
((Restaurant, RestaurantReview?), User?)
```

I would be interested in digging into this line of thinking further myself if it does not feel like too much of a compromise in how expressible the `QueryBuilder` is.

**Comment by tanner0101** [comment]
My only concern with that approach is that we would need to blindly convert all errors to `nil`, even if those errors may not be related to the values not existing. For example, if a joined model has a malformed UUID in a field, the error thrown would cause the entire model to become `nil`. This could make those errors really tough to track down. 

Looking forward, `alsoDecode` will likely be going away in Fluent 4 since you will be able to decode joined entities directly from the model. The API isn't final for this yet, but it will probably look something like:

```swift
let restaurants = try db.query(Restaurant.self)
    .join(\User.id, to: \Restaurant.userId, method: .left)
    .join(\RestaurantReview.restaurantId, to: \Restaurant.id, method: .left)
    .all().wait()
print(restaurants) // [Restaurant]

for restaurant in restaurants {
    let review = try restaurant.decodeJoined(RestaurantReview.self)
    let user = try restaurant.decodeJoined(User.self)
}
```

Here you could use `try?` to re-create the "fail on nil" behavior. But even better, we can add a method like `canDecodeJoined(_:)` or just make `decodeJoined(_:)` return an optional.

**Comment by mattpolzin** [comment]
Agreed that losing errors unrelated to the joined row not existing is a big bummer. I like the proposed direction for Fluent 4 quite a bit. I suspect I’ll end up pursuing this workaround for myself (accepting the inherent risks) as an interim solution but I understand the disinterest in adopting it for the Vapor project.

Thanks.

**Comment by jhheider** [comment]
As I was just bitten by this particular bug today myself, I'd love to see @mattpozlin's "decode or nil" solution. Before I figured out *why* I was doing it wrong, this was the behavior I was unconsciously expecting. It's definitely counter-intuitive that a LEFT JOIN with .alsoDecode() will always error, unless you didn't need it to be left at all.
