### ISSUE TITLE
SoftDeletable is commented out

### ISSUE THREAD

**Issue by nathantannar4** [vapor/fluent#558]
Any reason why SoftDeletable is commented out? There is reference to soft deletes everywhere but you cannot actually soft delete a model.

**Comment by grundoon** [comment]
`SoftDeletable` functionality has been moved directly into `Model` https://api.vapor.codes/fluent/latest/Fluent/Protocols/Model.html

but I suspect that the documentation is indeed a bit misleading at this point (https://github.com/vapor/fluent/blob/master/Sources/Fluent/Model/Model.swift#L74-L76), since the `SoftDeletable` protocol no longer exists. (@tanner0101 ?)

**Comment by nathantannar4** [comment]
True, but the `softDelete(on:)` method is gone

**Comment by grundoon** [comment]
So, soft deletion is now auto-magical if a `Model` has a `deletedAtKey` field – it's the default if that `TimestampKey?` is set. To override it, use the `force:` parameter https://github.com/vapor/fluent/blob/d17e5704a37d24cf26712d788fa4e24445b8b45a/Sources/Fluent/Model/Model%2BCRUD.swift#L42-L53

To see an example of how all this is used now, check out https://github.com/vapor/fluent/blob/35859a0036a10cadd33a2e6ec1862f89c8744b24/Sources/FluentBenchmark/Benchmarks/BenchmarkSoftDeletable.swift
