### ISSUE TITLE
Table in Database doesn't Alter Table 

### ISSUE THREAD

**Issue by TannerJuby1** [vapor/fluent#577]
In my Vapor project, I have a Model that I wanted to add a new variable to. After adding the variable to the Model file, the build runs fine, but the migration to the database (SQLite) does not alter the model's table and add the new column.

I have to go into the database and run an SQL statement directly, but this shouldn't this be handled by the migration?

**Comment by vzsg** [comment]
This is by design. Fluent tracks which migrations it has executed on the database (by the class name of the migration), and will not touch any classes that were run once. As things are now, there is no facitlity to compare what each migration does what steps need to be done to get there, etc.

If you have real data in your database, you should create new Migration-compliant classes for the new DB versions. See also: [here](https://docs.vapor.codes/3.0/fluent/migrations/#migrating-data). If you're early in your development, just nuke the DB.

---

Also, automatic migrations (either with the synthesized migration or calling `addProperties` yourself) are discouraged, as they will make your database changes non-repeatable.

**Comment by TannerJuby1** [comment]
@vzsg thanks for the response! So if you ever want to add a new variable to a model, you need to just create your own migration-complaint and add it to the config? Seems easy enough, thanks!

**Comment by tanner0101** [comment]
@TannerJuby1 yes, exactly. But as @vzsg mentioned, if you're early in development, just nuking the DB is the easiest option.

I also second @vzsg in recommending that you implement separate migrations from the get-go. Being explicit is very advantageous IMO.

**Comment by TannerJuby1** [comment]
@tanner0101 thanks!
