### ISSUE TITLE
Operator "~~" is not a known operator 

### ISSUE THREAD

**Issue by AKazm** [vapor/fluent#644]
Just wanted to let you know that Fluent apparently does not expose all declared SQL operators. 

`User.query(on: request).filter(\User.roleId ~~ roleIds)`

refuses to compile because "~~" is not a known operator.

Workaround: Declare operator by yourself.

```
infix operator ~~
User.query(on: request).filter(\User.roleId ~~ roleIds)
```

**Comment by tanner0101** [comment]
Hmm, that's strange. Both places that the `~~` operator is defined, there is an `operator` declaration:

https://github.com/vapor/fluent/blob/3/Sources/Fluent/QueryBuilder/QueryBuilder%2BOperators.swift#L100
https://github.com/vapor/fluent/blob/3/Sources/FluentSQL/SQL%2BContains.swift#L29

**Comment by AKazm** [comment]
Yep, double-checked that before I was opening an issue here!

**Comment by tanner0101** [comment]
![Screen Shot 2019-10-03 at 4 26 23 PM](https://user-images.githubusercontent.com/1342803/66161551-8bb52500-e5fa-11e9-8df2-efa9fe0a81d9.png)

Looks like that's not valid. Which makes sense since the access level of the `func` that implements the operator could conflict.

Do you have `import Fluent` explicitly in this file? 

This might be worth reporting as a bug report to Swift.

**Comment by AKazm** [comment]
No, but `FluentPostgreSQL`.

**Comment by tanner0101** [comment]
Try importing Fluent explicitly. It might be an issue with `@_exported`

**Comment by panpapryk** [comment]
Hi, I can confirm that importing Fluent explicitly solved that problem for me.
