### ISSUE TITLE
@Children error

### ISSUE THREAD

**Issue by jose46moreno** [vapor/fluent#679]
I have created a parent-child relationship between the following two models, with the following migrations and when I run the Postman screenshot to create a user, I get the error.

Model User:

<img width="401" alt="Captura de pantalla 2020-04-23 a las 18 40 12" src="https://user-images.githubusercontent.com/8105593/80125389-e3fd4580-8591-11ea-89bc-53aa037d4adb.png">

Model Height:

<img width="434" alt="Captura de pantalla 2020-04-23 a las 18 40 34" src="https://user-images.githubusercontent.com/8105593/80125437-f1b2cb00-8591-11ea-8ea4-16aee59df57b.png">

Migration User:

<img width="554" alt="Captura de pantalla 2020-04-23 a las 18 41 09" src="https://user-images.githubusercontent.com/8105593/80125489-042d0480-8592-11ea-9f12-6888f4b75936.png">

Migration Height:

<img width="556" alt="Captura de pantalla 2020-04-23 a las 18 41 31" src="https://user-images.githubusercontent.com/8105593/80125528-1149f380-8592-11ea-8e1b-6c1e8f6da8d1.png">

Request to create User:

<img width="239" alt="Captura de pantalla 2020-04-23 a las 18 42 16" src="https://user-images.githubusercontent.com/8105593/80125590-2e7ec200-8592-11ea-8dcd-cb822c2289e3.png">

Error:

[ INFO ] query create users input=[[username: "johnsmith", name: "John", password: "$2b$12$xHXMWlIiVJlsVX8JpzG8UuWnpU4lXFseV.WHow1Bh.xvbd.3HbGnq", email: "xxxxx@email.com", image: nil, updated_at: 2020-04-23 16:45:22 +0000, id: D6B703B3-E631-40D9-86AB-0CA0EAF02232, created_at: 2020-04-23 16:45:22 +0000]]
Fatal error: Children relation not eager loaded, use $ prefix to access: Children<User, UserWeight>(for: [user_id]): file /Users/josepfm/Library/Developer/Xcode/DerivedData/SSS-Backend-ehnubkdoiqqgavaksaeutibbozzm/SourcePackages/checkouts/fluent-kit/Sources/FluentKit/Properties/Children.swift, line 35

**Comment by tanner0101** [comment]
As the error says, unless the relation has been eager loaded, you may only access with the `$` prefix. For example:

```swift
model.myRelation // fatalError, not eager loaded
model.$myRelation.query(on: db).all() // works
```

This is because the relation must be fetched asynchronously.

**Comment by jose46moreno** [comment]
> As the error says, unless the relation has been eager loaded, you may only access with the `$` prefix. For example:
> 
> ```swift
> model.myRelation // fatalError, not eager loaded
> model.$myRelation.query(on: db).all() // works
> ```
> 
> This is because the relation must be fetched asynchronously.

But I'm not making any calls to get.

Remember that the error occurs when calling toPublic, not any query from the database, so please open the issue again, as this does not solve the problem.

Thank you.

**Comment by tanner0101** [comment]
> But I'm not making any calls to get.

Not sure what you mean by that. If you attempt to access an `@Parent` or `@Children` property that is not eager loaded, you will get a crash. That is expected. Those must be accessed using `$` prefix as I wrote in my last comment. 

So instead of `user.height` it must be `user.$height.query`.

> so please open the issue again, as this does not solve the problem.

I have closed this because it is neither a bug nor a feature request that needs to be tracked. We can continue to answer your questions even though it has been closed.

**Comment by 0xTim** [comment]
@jose46moreno you're implicitly making a call to the database in your `toPublic` function by attempting to access the property wrappers, which is why you're getting the error. I suggest that you pass a `Request` or `Database` object into your `toPublic` function and then load the required properties, or don't attempt to query them and just pass an empty array through directly
